repos:
- repo: https://github.com/psf/black
  rev: "23.1.0"
  hooks:
  - id: black
    language_version: python3.10
- repo: https://github.com/pycqa/isort
  rev: "5.12.0"
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/asottile/pyupgrade
  rev: "v3.3.1"
  hooks:
  - id: pyupgrade
    args: ["--keep-percent-format", "--py3-plus", "--py310-plus"]
- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.12.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "4.1"]
- repo: https://github.com/PyCQA/autoflake
  rev: "v2.0.1"
  hooks:
  - id: autoflake
    args: ["--in-place", "--remove-all-unused-imports", "--expand-star-imports", "--ignore-init-module-imports"]
- repo: https://github.com/mikicz/pre-commit-hooks-django
  rev: "v0.4.1"
  hooks:
  - id: check-untracked-migrations
  - id: check-absent-migrations
    always_run: false
    files: (models\.py$)|(.*models/.*\.py$)
    types: [ file, python ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-docstring-first
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: name-tests-test
    args: [ "--pytest-test-first" ]
    exclude: (base|factories|utils|conftest|fixtures|valgrind)
  - id: check-added-large-files
    args: ["--maxkb=2048"]
- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: "0.2.1"
  hooks:
  - id: sync_with_poetry
