# Generated by Django 4.1.5 on 2023-01-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiltify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
