# Generated by Django 4.1.5 on 2023-01-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0002_campaign_description_campaign_name_campaign_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="active",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="currency",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="image_alt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="image_height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="image_src",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="image_width",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="kind",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="remaining",
            field=models.IntegerField(null=True),
        ),
    ]
