# Generated by Django 4.1.5 on 2023-01-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiltify", "0003_reward_active_reward_currency_reward_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
