# Generated by Django 4.1.6 on 2023-02-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0007_campaign_keep_refreshing"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="campaign",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="tiltify.campaign"),
            preserve_default=False,
        ),
    ]
