# Generated by Django 4.1.6 on 2023-02-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0008_reward_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="supportable",
            field=models.BooleanField(default=True),
        ),
    ]
