# Generated by Django 4.1.6 on 2023-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0009_campaign_supportable"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="test_poll",
            field=models.BooleanField(default=False),
        ),
    ]
