# Generated by Django 4.1.6 on 2023-02-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0010_poll_test_poll"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
