# Generated by Django 4.1.7 on 2023-02-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0011_campaign_uuid_donation_uuid_reward_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="missing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reward",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="reward",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
