# Generated by Django 4.1.7 on 2023-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0012_reward_missing_alter_reward_amount_alter_reward_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
