# Generated by Django 5.0.2 on 2024-02-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiltify", "0013_campaign_published_at_campaign_retired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
