# Generated by Django 4.1.13 on 2024-02-18 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0016_reward_ends_at_reward_inserted_at_reward_starts_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="campaign",
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="Poll",
        ),
    ]
