# Generated by Django 4.1.13 on 2024-02-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0017_remove_poll_campaign_delete_option_delete_poll"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("test_poll", models.BooleanField(default=False)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tiltify.campaign")),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("total_amount_raised", models.DecimalField(decimal_places=2, max_digits=20)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tiltify.poll")),
            ],
        ),
    ]
