# Generated by Django 6.0.2 on 2026-02-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiltify", "0019_donation_poll_donation_poll_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="loaded_from_webhook",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
